name: Sync Notion to Markdown

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [notion_publish]

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          
      - name: Install dependencies
        run: yarn install

      - name: Sync Notion to Markdown
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: yarn sync

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "Sync content from Notion" || echo "No changes to commit"
          git push